### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by kshitij86** [kshitij86/wine-app#2]
To enhance the user experiece, add a splash screen following the app colors and style.

- [Font family used](https://www.1001fonts.com/advent-pro-font.html)
- App themes and colors in `globals/styles.js`

**Comment by Xaconi** [comment]
Hi! Can I get assign on this one?

**Comment by kshitij86** [comment]
Your contribution is welcome @Xaconi 

This has been assigned to you. Feel free to ask if you have any questions!

**Comment by RudrakshK** [comment]
Hi! Could I be assigned this issue ?
PS: I am from reddit ;)

**Comment by kshitij86** [comment]
@Xaconi you used the provided splash from the assets. I've tried using that one, it is not properly cropped and stretches too far on Android devices. We need a splash image that scales with device screen size (an SVG maybe?) using the same design as `splash.png`. Let me know if you have any queries regarding this.

**Comment by kshitij86** [comment]
@RudrakshK sure! Your contributions are welcome. Assigning this to you as well.

**Comment by Xaconi** [comment]
> @Xaconi you used the provided splash from the assets. I've tried using that one, it is not properly cropped and stretches too far on Android devices. We need a splash image that scales with device screen size (an SVG maybe?) using the same design as `splash.png`. Let me know if you have any queries regarding this.

Ok I'll try with an SVG. But the image of the splash screen I use is a modified one. Can you share a screenshot of an Android device on the splash screen?

EDIT: I attach an image how I see the splash screen on an iPhone

![image](https://user-images.githubusercontent.com/1944438/95002681-f6ff5180-05d6-11eb-86be-309f91868ef6.png)

**Comment by kshitij86** [comment]
Here. This is what it looks like.

The font is jagged and the text is too big.


![wine](https://user-images.githubusercontent.com/26821140/95019440-db3a9080-0654-11eb-982a-3127b7513b2b.jpg)

**Comment by kshitij86** [comment]
I guess it looks better on a larger display. Which device are you using @Xaconi ?

**Comment by Xaconi** [comment]
> I guess it looks better on a larger display. Which device are you using @Xaconi ? 

I'm using an iPhone SE (it's like an iPhone 5, kind of small). But it looks like (on the screenshot you post) when I have the splash image with the old asset. You're using the new one?

**Comment by Xaconi** [comment]
> I guess it looks better on a larger display. Which device are you using @Xaconi ?

@kshitij86 any updates on this?

**Comment by kshitij86** [comment]
@Xaconi The screenshot @RudrakshK posted seems to render properly. Once he makes the necessary changes, I guess we'll go with that. I've labelled both PRs as `hacktoberfest-accepted` though.
